name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set variables
      run: |
        echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    - name: install tools
      run : sudo apt update && sudo apt install -y build-essential automake gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libcppunit-dev 
    - name: configure
      run: ./configure
    - name: make
      run: make -j$(nproc) || make
    - name: move files
      run: install -Dp ./bash ./publish/bash-x86_64
    - name: make clean
      run: make clean
    - name: Configure for arm64
      run: ./configure --host aarch64-linux-gnu
    - name: make arm64
      run: make -j$(nproc) || make
    - name: move files
      run: install -Dp ./bash ./publish/bash-aarch64
    - name: Release and upload assets
      uses: softprops/action-gh-release@v0.1.6
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        files: |
          ./publish/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
